import { FundingPoolProps } from '@/types/funding';

export const fundingPools: FundingPoolProps[] = [
  {
    id: 'fund-1',
    tokenName: 'Morpheus Protocol',
    tokenSymbol: 'MORPH',
    tokenLogo: 'https://arweave.net/hQiPZOsRZXGXBJd_82PhVdlM_hACo1AtWc-MMRvV9nc',
    purpose: 'Development of DeFi yield aggregator and smart contract audits',
    fundingGoal: 500000,
    currentFunding: 324500,
    expectedROI: 145,
    contributors: 247,
    status: 'active',
    isContributed: true,
    userContribution: '5,000',
    userShare: '1.54%',
    expectedReturn: '7,250',
    marketCap: 24500000,
    minContribution: 100,
    createdAt: '2024-01-15'
  },
  {
    id: 'fund-2',
    tokenName: 'Quantum Bridge',
    tokenSymbol: 'QBRDG',
    tokenLogo: 'https://arweave.net/-KYBLbU5Ub5LZ5TrYvQnzw8PkfVwUmYKHA3U0SrZZNo',
    purpose: 'Cross-chain bridge infrastructure and security enhancements',
    fundingGoal: 750000,
    currentFunding: 612000,
    expectedROI: 180,
    contributors: 389,
    status: 'active',
    isContributed: true,
    userContribution: '8,500',
    userShare: '1.39%',
    expectedReturn: '15,300',
    marketCap: 43200000,
    minContribution: 250,
    createdAt: '2024-01-20'
  },
  {
    id: 'fund-3',
    tokenName: 'Solar Network',
    tokenSymbol: 'SOLR',
    tokenLogo: 'https://arweave.net/MciM5zGNYhhQnXnaJ9wYpVrfVPHYsQTcEu1aaBAZt7g',
    purpose: 'Layer 2 scaling solution development and testnet launch',
    fundingGoal: 1000000,
    currentFunding: 285000,
    expectedROI: 220,
    contributors: 156,
    status: 'active',
    marketCap: 18750000,
    minContribution: 500,
    createdAt: '2024-02-01'
  },
  {
    id: 'fund-4',
    tokenName: 'Alpha Finance',
    tokenSymbol: 'ALPHA',
    tokenLogo: 'https://i.imgur.com/lQC7VPR.png',
    purpose: 'Lending protocol expansion and multi-chain deployment',
    fundingGoal: 600000,
    currentFunding: 445000,
    expectedROI: 165,
    contributors: 298,
    status: 'active',
    marketCap: 76200000,
    minContribution: 200,
    createdAt: '2024-01-10'
  },
  {
    id: 'fund-5',
    tokenName: 'Nexus Chain',
    tokenSymbol: 'NEXUS',
    tokenLogo: 'https://i.imgur.com/qC7ZRzw.png',
    purpose: 'Gaming platform development and NFT marketplace integration',
    fundingGoal: 850000,
    currentFunding: 725000,
    expectedROI: 195,
    contributors: 412,
    status: 'active',
    marketCap: 134000000,
    minContribution: 150,
    createdAt: '2024-01-25'
  },
  {
    id: 'fund-6',
    tokenName: 'Velocity Protocol',
    tokenSymbol: 'VLCTY',
    tokenLogo: 'https://arweave.net/o-SJorE41_4H5YqUD9tKLUfUiCAHEHwTZVUtJJIrLg0',
    purpose: 'High-speed transaction layer and enterprise partnerships',
    fundingGoal: 400000,
    currentFunding: 400000,
    expectedROI: 135,
    contributors: 189,
    status: 'funded',
    endDate: '2024-02-15',
    marketCap: 89500000,
    minContribution: 100,
    createdAt: '2023-12-20'
  },
  {
    id: 'fund-7',
    tokenName: 'Echo Network',
    tokenSymbol: 'ECHO',
    tokenLogo: 'https://i.imgur.com/5ufENCW.png',
    purpose: 'Decentralized social media platform and content creator tools',
    fundingGoal: 300000,
    currentFunding: 300000,
    expectedROI: 120,
    contributors: 234,
    status: 'funded',
    endDate: '2024-01-30',
    marketCap: 28400000,
    minContribution: 50,
    createdAt: '2023-12-10'
  },
  {
    id: 'fund-8',
    tokenName: 'Prism Finance',
    tokenSymbol: 'PRISM',
    tokenLogo: 'https://i.imgur.com/iGyPPJT.png',
    purpose: 'Derivatives trading platform and liquidity mining incentives',
    fundingGoal: 650000,
    currentFunding: 650000,
    expectedROI: 175,
    contributors: 367,
    status: 'funded',
    endDate: '2024-02-10',
    marketCap: 187500000,
    minContribution: 300,
    createdAt: '2023-12-05'
  }
];
